import { SignIn, SignInButton, useUser } from "@clerk/nextjs";
import { type NextPage } from "next";
import Head from "next/head";
import { PostsView } from "~/components/Posts.component";
import { LoginUser } from "~/components/userLogin.component";

import { api } from "~/utils/api";

const Home: NextPage = () => {
  // const hello = api.example.hello.useQuery({ text: "from tRPC" });
  const { data } = api.posts.getAll.useQuery();
  const user = useUser();
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex h-screen items-center justify-center">
        <div className="h-full w-full md:max-w-2xl">
          {user.isSignedIn ? <LoginUser user={user.user} /> : <SignInButton />}
          <SignIn path="/sign-in" routing="path" signUpUrl="/sign-up" />
        </div>
        {data?.map((postDetails) => (
          <PostsView key={postDetails.post.id} {...postDetails} />
        ))}
      </main>
    </>
  );
};

export default Home;
