import { SignIn, SignInButton, useUser } from "@clerk/nextjs";
import { type NextPage } from "next";
import Head from "next/head";
import { type ChangeEvent, type FormEvent, useState } from "react";
import { AddTweet } from "~/components/addTweet";
import { PostsView } from "~/components/Posts.component";
import { LoginUser } from "~/components/userLogin.component";

import { api } from "~/utils/api";

const Home: NextPage = () => {
  // const hello = api.example.hello.useQuery({ text: "from tRPC" });
  const { data } = api.posts.getAll.useQuery();
  const user = useUser();
  const [tweet, setTweet] = useState("");
  const handleChange = (e: ChangeEvent<HTMLInputElement>) => {
    setTweet(e.target.value);
  };
  const handleSubmit = (e: FormEvent) => {
    e.preventDefault();
  };
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex h-screen flex-col">
        <div className="w-full md:max-w-2xl">
          {user.isSignedIn ? <LoginUser user={user.user} /> : <SignInButton />}
          <SignIn path="/sign-in" routing="path" signUpUrl="/sign-up" />
        </div>
        <AddTweet
          imgSrc={user.user?.profileImageUrl ?? ""}
          val={tweet}
          handleChange={handleChange}
          handleSubmit={handleSubmit}
        />
        <div className="flex flex-col">
          {data?.map((postDetails) => (
            <PostsView key={postDetails.post.id} {...postDetails} />
          ))}
        </div>
      </main>
    </>
  );
};

export default Home;
